### ISSUE TITLE
Cipher detection interface

### ISSUE THREAD

**Issue by Cyclic3** [Ciphey/Ciphey#104]
### Problem
We have a limited number of ciphers that can be detected, and adding a new one means retraining the AI. Also, some ciphers can be detected far more easily algorithmically, and encodings can be checked by attempting to decode them.

To fix this problem, we have a tacked-on interface for filtering out various encodings, but that does;n't solve the root problem.

However, the AI does provide us with an order of testing, which would be hard to replicate

### Solution
Present an interface like the following:
```python
from abc import ABC, abstractmethod
from typing import Optional, Dict

class Decoder(ABC):
    """Represents the undoing of some encoding"""
    @staticmethod
    @abstractmethod
    def decode(self, ctext: str, config: Dict[str, object]) -> Optional[str]: pass

class Cracker(ABC):
    @staticmethod
    @abstractmethod
    def scoreLikelihood(self, ctext: str, config: Dict[str, object]) -> float:
        """This should give a probability of this being this cipher"""
        pass
    @staticmethod
    @abstractmethod
    def attemptCrack(self, ctext: str, config: Dict[str, object]) -> Optional[str]:
        """This should attempt to crack the cipher, and use the config["checker"] where appropriate"""
        pass
```

The new steps should be
1. Ciphey should gather in a collection of modules exposing various `Decoder`s and `Cracker`s
2. Ciphey should apply all the `Decoder`s it can to the ciphertext, and store this in a list
3. It should then walk through all the crackers, running `scoreLikelihood` on all of the decoded ciphertexts, applying `attemptCrack` to ones with a likelihood above a certain threshold, and storing the remaining ones in a collection ordered by likelihood. 
4. If we still haven't got anything, give up

**Comment by brandonskerritt** [comment]
Hey! Just some notes before I talk about this some more.
1. Training the AI is hard
The AI does know specific algorithms, you're right. And it is a pain to re-train it (I'm talking 2+ days of training on a sufficient dataset). However, Ciphey (not the AI) knows that "Base64" could mean any of the base decodings, so it tries that. However! If for example we had cipher X and cipher Y, both in the same "family" (maybe substitution?) but they were sufficiently different enough the neural network might not notice that cipher Y "looks" similar to cipher x (this is how it currently works. It assumes Vigenere looks like Caesar, Base64 looks like Base16, Sha1 looks like Sha512). 

I was thinking there must be some way to teach the NN what a "family" of ciphers looks like in general, and to apply that instead. So it would learn that Base encodings have, for example:
* Usually have an "=" or "==" on the end
* Are fixed char sets
* No spaces
And instead of saying "this is base64", it says "this belongs to the Base family". 

**This becomes much more important** if we were to build an interface to easily code other ciphers. At the moment, it is _rather_ simple but kind of long-winded and might be confusing to those that do not understand the code base. 

2. The idea of the interface itself (mainly the code)
This is basically how the parent classes work, see `basicParent.py`. Ciphey does these things:
* Collect all the objects for decryption into a list
* Multi-thread for every object in list:
    * run list[i].decrypt()
If I am not mistaken, this is suggesting to do that but for every cipher Ciphey has. These has some benefits:
* Bringing the decryptions physically closer to the edge, meaning Ciphey will not have the overhead of creating multiple parent classes and traversing through the file system to build new objects.
* Much easier to create new encryption objects. We can create a new encryption object like we do already with parent classes, except this time we only have to worry about one interface for all.
* By having one single interface to control all objects, we can easily build a 2nd layer decrypting system. So if something is caesar(base64("hello")) it would be much easier to decrypt with this method
* Using this class, we can easily store "likely" decryptions which didn't quite make it past language checker, allowing the user to select their own answer from the given list.

**The way we could build this instead is:**
1. Ciphey should gather in a collection of modules exposing various Decoders and Crackers
2. Ciphey should apply all the Decoders it can to the ciphertext, and store this in a list
^^ so long as decoding is physically fast, this shall be okay. There are some such as morse code which _may_ be a little slow given a large text, but should be okay.
3. **Ciphey can use the neural network / simple filtration system as the likelihood score. The neural network _only_ returns those candidates with the highest likelihood, nothing else. To use this likelihood, we simply need to call `obj.name` on each cipher to get the string name of it and then match these with the dictionary string names. Once it has done this, we simply remove every item from the list of crackers / decoders which intersect with the probability distribution. **
4. **If we still haven't gotten anything, and if we're in non-grep mode, return information to the user which may help them manually decrypt / decode the cipher. We have information such as the simple regex system and the neural network, it would be useful for us to return this kind of information to inform the user about the cipher.**

**Comment by Cyclic3** [comment]
I think moving the AI to classify *families* of ciphers is a great idea! It has proven to be remarkably effective an

I would, however, like to address some of your points:

"Applying" a decoder should be low overhead if the decoder doesn't match. Your example of a morse decoder slowing it down would only apply if it was encoded in something that looked like morse, which would probably mean that it *was* morse.

Whilst we're on that topic: SHA1 only looks like SHA512 when you have no idea how long the actual datastream is, as they both look like random data. If we cannot decode it, then we haven't a hope in hell of cracking it, and if we can, then we can tell which one it is. The insight provided by the AI is minimal on that, unless it has somehow managed to find a way of distinguishing hashes from random data, in which case the Journal of Cryptology is probably a better place to discuss this :p

I still believe there should be implementations that circumvent the AI completely. For instance, DES can be distinguished from random data by some difficult statistical analysis that the AI will not be able to learn.

Taking on board the points you raised, I would like to propose yet another alternative scheme:
```python
class Detector(ABC):
    @abstractmethod
    def what(self) -> str:
        """Returns the cipher that this object attempts to detect"""
        pass
    @abstractmethod
    def scoreLikelihood(self, ctext: str, config: Dict[str, object]) -> Dict[string, float]::
         """Should return a dictionary of (cipher_name: score), using config["checker"] as appropriate"""
    @abstractmethod
    def isIntensive(self):
        """Return True if this will take a significant amount of time by some metric

class Cracker(ABC):
    @abstractmethod
    def what(self) -> str:
        """Return the cipher that this object attempts to crack"""
        pass
    @abstractmethod
    def attemptCrack(self, ctext: str, config: Dict[str, object]) -> Optional[str]:
        """This should attempt to crack the cipher, and use the config["checker"] where appropriate"""
        pass
```
(the `Decoder` interface remains the same)

The `family` AI should be a `Detector` that returns the score for each family, maybe scaled to get it to hit the threshold on particularly likely outputs.

Anyway, here is the algorithm:

1. We gather the `Decoder`s, `Detector`s,  and `Cracker`s from the various modules. When we gather the non-`Cracker` objects, we put them in a structures of type `Dict[str, List[OBJECT_NAME]]`, which allows simple lookup, and keep intensive detectors separate.
2. We then iterate through the non-intensive ones in parallel, storing the results in `scores: Dict[str, float]`, which will keep track of the probabilities as we go through. 
   * If we get a scores above some threshold (maybe use 1 or something), we should attempt the crackers for that, and remove that entire cipher from the system (by deleting it from the relevant dictionaries).
   * If we do not exceed the threshold, look it up in `scores`, and if our score is above the existing value, update it with the new one.
3. If we exhaust the non-intensive detectors, we then iterate through the intensive ones in the same way, using the same `scores` dictionary.
4. Now we sort the `scores` dictionary into a list, and iterate through them in descending order, until we run out of ciphers.

This could perhaps be improved by also taking into account the complexity of cracking, but I'm not sure how to do that without massively overcomplicating the algorithm. We can hopefully rely on more secure algorithms being harder to detect instead :p

**Comment by brandonskerritt** [comment]
Great algorithm and rebuttal! When we store them in point 2, we should perhaps try to do an insertion / merge sort on them while we are adding them to the dictionary. This will save us time from sorting it in point 4 :)

**Comment by brandonskerritt** [comment]
@Cyclic3 Not entirely related to this issue, but I am seeing a repeated pattern here. Multiple different alphabets for the same encryptions (bases, morse code). Along with #77 and possibly #105 . I propose that when we call a cipher, since we have them in an easy interface like so we should exhaust the cipheyDists lists for that type. We should try to aim to use the same code, but supply the arguments repeatedly. Like a for loop through the possible char sets?

For what its worth, Morse Code has about 455 different possible alphabets (for English alone). There's certain standards (what is used in the Navy, what is used by online encoders, what is taught in survival books). 

I know that Base has the same.

Should we find out the most popular char sets, and use them, or should we go through them all?
Would it be worth first doing the most popular ones, and then falling back onto all of them if we cannot find the answer?

**Comment by brandonskerritt** [comment]
Another idea:

We assign "cost" to each decryption method (number of computations) and then we can do an A* search, using heuristics such as the neural network and filtration system to work out how likely something is. So we have a likely chance / computational cost, and we do the things first that are more likely but cost less. 

Essentially, we are combining accuracy & speed into one. So we:
* assign a cost to each decryptor based on number of computations
* we delete those filtered out by simple filtration
* We begin encoders()
* We use the likelihood function to determine the likelihood of something. 
* We do all the ones that are both low cost / high likelyhood. We sort both of them, so we can divide them (computational cost / likelihood chance) which means that if something costs 90, but it is 80 it is low. But if something costs 10, and we have 90 likelihood we have even lower score.

Alternatively, we can train a neural network to do this for us. We can teach it how long a cipher takes, while teaching it to identify ciphers. the return score is the combined heuristic seen above.

**Comment by SkeletalDemise** [comment]
Closing this because Ciphey's interface was finished a long time ago.
