### ISSUE TITLE
PyPi version is incredibly slow

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#115]
```
➜ ciphey -t "NBSWY3DPEBUSAYLNEBQSA2DVNVQW4IDBNZSCA2JANRUWWZJAMNQXI==="
┏━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Name of Cipher ┃ Probability ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ Caesar         │      58.03% │
│ Plaintext      │      39.72% │
│ Base           │       2.25% │
└────────────────┴─────────────┘
hello i am a human and i like cat

~/Documents via 𝗥 v1.43.1 via test8 took 10s
➜ c

Ciphey on  master [⇣!] via ciphey via 🐍 system
➜ python3 ciphey -t "NBSWY3DPEBUSAYLNEBQSA2DVNVQW4IDBNZSCA2JANRUWWZJAMNQXI==="
┏━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Name of Cipher ┃ Probability ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ Caesar         │      58.03% │
│ Plaintext      │      39.72% │
│ Base           │       2.25% │
└────────────────┴─────────────┘
hello i am a human and i like cat
```
PyPi vs local

**Comment by brandonskerritt** [comment]
https://i.imgur.com/Koo9Rti.gifv
from @michalani

**Comment by brandonskerritt** [comment]
For my example in the original issue, it look 10 seconds to decode that base string, whereas locally it took < 3 seconds.

**Comment by brandonskerritt** [comment]
Here's a better show case using the `time` module:
```
hello i am a human and i like cat
ciphey -t "NBSWY3DPEBUSAYLNEBQSA2DVNVQW4IDBNZSCA2JANRUWWZJAMNQXI==="  8.64s user 1.43s system 91% cpu 11.000 total
```
^^ PyPi version
```
python3 ciphey -t "NBSWY3DPEBUSAYLNEBQSA2DVNVQW4IDBNZSCA2JANRUWWZJAMNQXI==="  1.80s user 0.54s system 75% cpu 3.099 total```

**Comment by brandonskerritt** [comment]
Possibly, this may be caused by Pip installed apps having a limit on the number of threads? _maybe_? It's the only thing I can think of

**Comment by Cyclic3** [comment]
I have an AMD threadripper, so you would think that multithreading would give me more benefit that most. However, I actually see performance *degradation* when I use the threads. I do not believe it is that.

It could be something to do with the manylinux2014 image I am forced to build on. I would *like* to statically compile it with the latest libs, but unfortunately it complains when I do that (if anyone knows how to get around that, please file it!)

I cannot repro this slowness everyone is talking about, so can people check they have the *latest* version 4.2.0? I'm going to add a -V/--version flag so that people can report this more easily!

**Comment by Cyclic3** [comment]
On checking your output, you are definitely using an old version. This is most likely due to the borked versioning in #117. I'm going to mark this as "invalid" until it is shown in ciphey 4.2.0 using the latest cipheycore
