### ISSUE TITLE
Strings that can be decoded / cracked in 2 crackers / decoders

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#143]
```
ciphey -t "IkknbSBnb2luZyB0byBtdXJkZXIgdW5jbGUgYm9iIGF0IDZwbSB0b21vcnJvdw=="┏━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Name of Cipher ┃ Probability ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ Base           │      99.99% │
└────────────────┴─────────────┘
```

This is a base 64 string, but it returns as SHA256. 
```
Returning {'lc': None, 'IsPlaintext?': True, 'Plaintext': 'CODE ERREUR : 005', 'Cipher': 'sha256', 'Extra Information': None}
```

This is because:
1. The string is the exact right size for SHA256
2. It just so happens, on one of our hash APIs, that the string has been calculated to be that.

**Comment by Cyclic3** [comment]
This *is* a difficult situation. 

Luckily, there are some things we can do with the (almost finished) cipher-iface branch!

Since a hash is binary data, AuSearch will decode the base64, and first check for further decodings. The chance of a SHA256 hash successfully decoding as UTF-8 is roughly 1 in 2^32 (4 billion). Even if someone really is that unlucky, that just means that we will waste time with that string, before cracking the hash. 

Conversely, if it really is a UTF-8 string, any reasonably accurate AuSearch heuristic will leave the intensive sha256 cracking until later in the search. 

One suggestion would be to add a tag system for the crackers, so that a user could disable/single out hash cracking, without having to rewrite large portions of the code base.

I would be interested to see people's feedback after Orwell is released, so that we can see whether this is worth implementing.

**Comment by brandonskerritt** [comment]
SHA256 is not cracked, it is searched up in an API - thus it is **much** faster than everything apart from the decoders. :disappointed: 

I'm hoping this fixes it:
> Since a hash is binary data, AuSearch will decode the base64, and first check for further decodings. The chance of a SHA256 hash successfully decoding as UTF-8 is roughly 1 in 2^32 (4 billion). Even if someone really is that unlucky, that just means that we will waste time with that string, before cracking the hash.

**Comment by Cyclic3** [comment]
Ausearch is now reasonably accurate, so this should not be a problem anymore
