### ISSUE TITLE
Please provide more information on how to install Ciphey

### ISSUE THREAD

**Issue by Veeyu22** [Ciphey/Ciphey#145]
I've been coming back to this page trying to get Ciphey to work over and over and I'm simply not knowledgable enough to get it to work.
I downloaded a release of Ciphey, put it in a folder and put it on my desktop, then checked the installation section.
It basically tells me to run 

> python3 -m pip install -U ciphey

Okay, so, I downloaded python 3, restarted my pc, and the command doesn't work, turns out, I had to change it to

> python -m pip install -U ciphey

Because I was upgrading from a previous version of python. Then, I kept getting:

> ERROR: Could not find a version that satisfies the requirement cipheycore<0.2.0,>=0.1.4 (from ciphey) (from versions: 0.0.1, 0.1.0)
> ERROR: No matching distribution found for cipheycore<0.2.0,>=0.1.4 (from ciphey)

And, of course, running

> ciphey -t "encrypted text here"

won't do anything, because it didn't install correctly. So I decided to check out https://docs.ciphey.online/en/latest/ to try and understand what I was doing wrong. 
The installation page there is completely different, telling me to run 

> $ pip3 install ciphey

Not only does CMD not run like this but it doesn't give me any links as to what pip3 comes from or what I need to run the command to begin with. Running the command returns another error

> ERROR: Could not find a version that satisfies the requirement tensorflow<3.0.0,>=2.1.0 (from ciphey) (from versions: none)
> ERROR: No matching distribution found for tensorflow<3.0.0,>=2.1.0 (from ciphey)

Ciphey looks amazing, but for someone like me who basically knows nothing about running python scripts and such, it's a complete maze to get working because of the lack of information. And even worse for someone who doesn't know the basics.
Just telling users to "run commands" is a bit.. hollow. For a total noob. 
So I'm basically forced to admit to being a bit stupid and just ask you guys to provide more information on the installation page for people like me, or to just help me directly.

**Comment by Cyclic3** [comment]
Hi there, thanks for reporting this issue! So many people in this situation silently give up, and then we never find out!

The main problem there is that your system is failing to install two packages, cipheycore and tensorflow. These packages are both binary packages, which have to be compiled for each version of python it supports, and so it is likely something to do with your python version.

Could you send us the output of `python -c "import sys; print(sys.version)"`

**Comment by Cyclic3** [comment]
Also, the lack of documentation is a really big problem, and if people aren't even able to install ciphey, we REALLY need to prioritise it. Over the next week, @brandonskerritt and I will be writing a lot of docs, don't worry 🙂

**Comment by Veeyu22** [comment]
output:

> 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]

Glad to hear from you guys, there's the output running the command you gave me.

**Comment by brandonskerritt** [comment]
Hey!

In response to your comment, I wrote an installation guide which explains what Pip and Python is and why we need them. However, I don't think it'll help you very much other than learning what Pip is :smile:
[https://docs.ciphey.online/en/latest/install.html](https://docs.ciphey.online/en/latest/install.html)

I'm just going to copy and paste your issues, so I can more easily see them:

```
ERROR: Could not find a version that satisfies the requirement cipheycore<0.2.0,>=0.1.4 (from ciphey) (from versions: 0.0.1, 0.1.0)
```

```
ERROR: Could not find a version that satisfies the requirement tensorflow<3.0.0,>=2.1.0 (from ciphey) (from versions: none)
```

So, a quick explanation:

pip is the software used to install packages in Python, think of it as like an app store for the command line.

We tell users to run pip through Python `python -m pip` since users can have many versions of Python installed, and we want the _main_ Python version. This solves a lot of headaches.

Also, since your default Python is `3.8.3`, that means `pip3` and `python -m pip` are the same command :smile_cat: 

Our 'app' Ciphey, relies on other 'apps' to be downloaded through Pip.

We tell your version of pip what apps to download, through something called a `requirements.txt` file.

This file is just a list, like:

```
cipheycore
tensorflow
```

Your version of pip couldn't find the apps to download them. Or it could, but it could only find older versions.

Side note: pip apps are called packages, but that's kind of confusing for someone that's new to Python, as Python uses a lot of wacky terminology.

There are somethings that may have caused this.

1. We messed up our list of apps we want (our fault)
2. Your version of pip is out dated (Python's fault)
3. Something has happened and we don't know how to explain it (our fault, again)

The easiest solution may be to upgrade pip, so we'll try that first.

Can you please run :sparkles: 

```
python -m pip install --upgrade pip
```

This tells pip to upgrade the app 'pip', which is just itself.

Then try to re-install Ciphey with:

```
python -m pip install -U ciphey
```

Since pip may be older, it may not have found the packages to install. This _might_ fix it.

If that didn't fix it, let's go through some more things.

The 2nd reason might be that our `requirements.txt` has messed up. Which is our fault, sorry!

With your new upgraded version of pip, let's try to **manually** install the apps. Don't worry, it's not as hard as it sounds! We just ignore the requirements, and install them by hand.

This may come in handy in the future, for any Python apps that don't want to help you try to install it.

Every Python package (or app) is on PyPi.

You don't have to follow along, but I'll show you how to fix this problem in the future in case other developers aren't as nice.

CipheyCore is located here. [https://pypi.org/project/cipheycore/0.1.5/](https://pypi.org/project/cipheycore/0.1.5/). You can just search for the package name and find it.

Now click on "release history" on the left and you'll see a list:

![image](https://user-images.githubusercontent.com/10378052/86530362-1c819f80-beb0-11ea-8a27-560284325577.png)

Your error says this:
> ERROR: Could not find a version that satisfies the requirement cipheycore<0.2.0,>=0.1.4 (from ciphey) (from versions: 0.0.1, 0.1.0)

So we want a version between 0.1.4 and 0.2.0.

The "rc" part of the version number means "release candidate", as in it is being tested. So we don't want that.

Let's install Cipheycore 0.1.5.

When you click on it, you'll see a command below `cipheycore` which tells you how to install it:
![image](https://user-images.githubusercontent.com/10378052/86530397-518df200-beb0-11ea-961b-ab665b5813e0.png)

Now, we're using python and pip together. So **run this command**:

```
python -m pip install cipheycore==0.1.5
```

Now the 2nd issue you faced is Tensorflow. This is concerning, as Google maintains Tensorflow and if Google is having issues, that's very scary for us!

Try to install it without a specific version, such as:

```
python -m pip install tensorflow
```

If these installs don't work, try one more time with `-U`.

```
python -m pip install -U cipheycore==0.1.5
```

And then try to re-install Ciphey:

```
python -m pip install -U ciphey
```

Note: the install is 500mb, but the newest version of Ciphey (not yet released to the public) is ~20mb. If this puts you off, please watch the repo to find out when we release the much smaller Ciphey version :)

If these 2 things do not work, let us know! And we will dig out a Windows computer and try it ourselves :D 

For @Cyclic3 For the installation blog post, I'm going to write:

```
python -m pip install -U ciphey==4.2.0 cipheycore==0.1.5 cipheydists==0.3.4
```

Since each version of the docs is now in line with the repo, we can use package pinning to specify the exact versions which _may_ avoid issues like this in the future. I do not want to put this onto the main repo, as it is kind of a messy command. But, I will make sure it is #1 command in our trouble shooting guide :100:

**Comment by brandonskerritt** [comment]
I'm talking to someone else right now who has the same issue:
![image](https://user-images.githubusercontent.com/10378052/86546839-922c5080-bf2e-11ea-9af9-52be96e59086.png)

**Comment by brandonskerritt** [comment]
@Veeyu22 Please can you confirm your operating system, and your CPU. Or maybe if you're on a Raspberry Pi? Tensorflow, the package you had a problem with, isn't available for every device :(

**Comment by Veeyu22** [comment]
I'm on Windows 10, running the leatest build of windows 10. My CPU is an i5-6400

**Comment by Veeyu22** [comment]
Fix 1 step one: 

> Requirement already up-to-date: pip in c:\users\alexs\appdata\local\programs\python\python38-32\lib\site-packages (20.1.1)

Fix 1 step 2: (simply returns error as nothing has changed)

> ERROR: Could not find a version that satisfies the requirement tensorflow<3.0.0,>=2.1.0 (from ciphey) (from versions: none)
> ERROR: No matching distribution found for tensorflow<3.0.0,>=2.1.0 (from ciphey)

To save time, I decided to just go through all of them and only mention when something worked. All of fix 1 and two resulted in errors.

I also tried installing the wheel files directly. I did cd to the location of the file and ran a command to download it and I got this error:

> C:\Users\name\Documents>pip install cipheycore-0.1.5-cp35-cp35m-win_amd64.whl
> Fatal error in launcher: Unable to create process using '"c:\users\name\appdata\local\programs\python\python38-32\python.exe"  "C:\Users\name\AppData\Local\Programs\Python\Python38-32\Scripts\pip.exe" install cipheycore-0.1.5-cp35-cp35m-win_amd64.whl': The system cannot find the file specified.

**Comment by Veeyu22** [comment]
After doing a bit of looking, Tensorflow or Tensorflow-gpu is supported only for 3.5.X versions of Python, so I'm going to try changing versions. I'll keep you posted.

**Comment by brandonskerritt** [comment]
Hey Vee,

I read that Tensorflow doesn't support 32 bit versions. I think _maybe_ your Python install is 32 bit. although I am in bed and cannot confirm this.

Can you pretty please install Python 3.8 64 bit version?

And then:

Upgrade pip (using python 3 -m pip install --upgrade pip)

and then try to install tensorflow manually:
pytjon3 -m pip install tensorflow

We are releasing a version without tensorflow very very soon, so hopefully this problem won't persist. :)

**Comment by Veeyu22** [comment]
Ah, okay, yeah the thread was outdated and I was coming here to mention that, sorry about that. Alright, I'll install a 64bit version

**Comment by brandonskerritt** [comment]
🤞 let's hope this fixed it! If not, we are maybe a week max away from releasing a non tensorflow version 😜

**Comment by Veeyu22** [comment]
It's looking very promising. 
![victory](https://user-images.githubusercontent.com/42015732/86669086-1ff85200-bfa8-11ea-96dd-968ad0ae9040.PNG)
all of this because of this button
![problems](https://user-images.githubusercontent.com/42015732/86669122-28508d00-bfa8-11ea-8ac6-740ee41bb499.PNG)

**Comment by Veeyu22** [comment]
![yayyyyyyy](https://user-images.githubusercontent.com/42015732/86672323-6307f480-bfab-11ea-87a4-d26e0cf40090.PNG)

**Comment by brandonskerritt** [comment]
all-contributors add @Veeyu22 for documentation and bugs

1. Without you mentioning this bug on our repo, we would have had many users just give up
2. I have tried for weeks to convince @Cyclic3 to write documentation and this has convinced him how important it is
3. Our first GitHub issue from someone not on the Dev team! 🎉

Your GitHub profile will be placed on the README as soon as I wake up.... 😜

**Comment by brandonskerritt** [comment]
@all-contributors add @Veeyu22 for documentation and bugs

1. Without you mentioning this bug on our repo, we would have had many users just give up
2. I have tried for weeks to convince @Cyclic3 to write documentation and this has convinced him how important it is
3. Our first GitHub issue from someone not on the Dev team! 🎉

Your GitHub profile will be placed on the README as soon as I wake up.... 😜

**Comment by Cyclic3** [comment]
This seems to be sorted, thanks for the bug report!
