### ISSUE TITLE
Out there idea: rewrite Ciphey in Rust

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#165]
This is an out there idea, for maybe a good couple months / a year.

There are 4 distinct advantages to Rust that would help Ciphey a lot:
1. C++ performance
Rust has near or same C++ performance.
2. Rust is compiled
Rust is compiled and can compile binaries for Windows, Mac OS, and Linux very easily.
3. Rust's safety 
Rust takes safety as it's #2 issue, right next to speed. The compiler tries incredibly hard to stop the programmer from writing unsafe code.
4. **Web Assembly.**
Rust can be compiled into web assembly code, which means the code runs **in-browser, client side**.
Effectively, we'd get C++ performance **client-side**. Web Assembly native integrates with Javascript, so we can build pretty websites with it too.
If Ciphey is written in Rust, we can have **client-side C++ performance of Ciphey**. It's so cool I just had to mention it multiple times!

**Comment by Cyclic3** [comment]
I used rust as my primary language for a year.

Then I stopped.

I will not make a long anti-rust rant (in fact, I believe there are things it is better at). Instead, it suffices to say that forcing programmers to use a counter-intuitive coding style is not the best way of getting more contributors.

I would argue against using any non-python language (and I hate myself for saying this) because python is *easy*. Most people who use ciphey could write a module for it, with minimal effort.

We do limited multithreading in Ciphey, and all of the multithreading is done in the core (in C++). All of the stuff we do in python is quicker than the time taken to create a new thread, so I really don't think that would help too much. Some things (like the search algorithms) may not even receive a linear speed improvement!

I have made multithreading mistakes in my life, and I wouldn't be surprised if they appeared in the future in the core, but since this is basically just parallelised cracking, the worries of resource safety do not really apply. We do not have complex provider/consumer queues, we do not have user input and we do not have heavily generic code.

Webassembly is more of a feature of *clang*, not Rust. emscripten exists for C++ if this is something we want to do.
