### ISSUE TITLE
Endless loop on simple base64 encode

### ISSUE THREAD

**Issue by Alexeyan** [Ciphey/Ciphey#317]
**Describe the bug**
When evaluating ciphey against a simple base64 encoding it runs for a while and then freezes. 
-vvv shows that it at one point successfully decodes the file but then tries more encodings and ciphers and dies after trying Vignere.

**To Reproduce**
ciphey -f <(cat /etc/passwd | base64) -vvv

**Expected behavior**
Base64 decoding into something that is mostly valid english should succeed fast and not crash or freeze.

**Comment by brandonskerritt** [comment]
What is the exact plaintext? :) 
I think it's because the plaintext is not one of these:
1. English
2. JSON
3. You didn't include a crib
Ciphey cannot tell when something is plaintext or not unless we program that in, we do this using "checkers". Programs like CyberChef only do encodings, which means they expect one input to equal one output. In Ciphey, it is very possible for Base64 to perfectly decrypt as Caesar cipher, or for Viginere to decrypt as a hash (we have seen both of these cases before).

Because one input can equal many outputs, we have to use `checkers`. If you know roughly what the input will contain, please use the Regex checker which will act as a crib and allow Ciphey to find it effectively.
