### ISSUE TITLE
running ciphey get ImportError：image not found

### ISSUE THREAD

**Issue by LronDC** [Ciphey/Ciphey#364]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [yes ] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
running ciphey -t "" get ImportError: image not found

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
gAAAAABc8O567F0sIQn1FgbD8NOZdPrJvxIhJcLl1CNMz7lmFYwEMB9lX_t4jd5SE_tNZUB_zPyjlaAe8JMO63pB9H5ktpQkAw==
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: MacOs Catalina 10.15.6
 - Python version: Python 3.7.7
 - Ciphey versions: 
Name: ciphey
Version: 5.3.2
---
Name: cipheycore
Version: 0.2.9
---
Name: cipheydists
Version: 0.3.23
 - Did you use Docker? No

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)
https://pastebin.com/a3JPg4ud

**To Reproduce**
1. What input did you use? gAAAAABc8O567F0sIQn1FgbD8NOZdPrJvxIhJcLl1CNMz7lmFYwEMB9lX_t4jd5SE_tNZUB_zPyjlaAe8JMO63pB9H5ktpQkAw==
2. What flags / arguments did you use? -t

**Expected behavior**
decrypted string
**Any other information?**
I installed it in a conda environment, use python 3.7 and pip 19.0
![Uploading image.png…]()

**Comment by SkeletalDemise** [comment]
If you had read this page (https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions), you would see that this is an already known issue with Mac OS, and is solved by using Docker.

I am closing this because this is a duplicate issue and we already have instructions on how to install Docker in the documentation. If you encounter any bugs using Ciphey with Docker, you can make a separate issue and if you need support we have a Discord.
