### ISSUE TITLE
Missing underscores while decoding a Atbash string.

### ISSUE THREAD

**Issue by 547y4m** [Ciphey/Ciphey#518]
- [ ] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)
---->Yes

**Describe the bug**
-----> Underscores are neglected while outputting decoded string which is encoded with atbash cipher. 

**Plaintext**
```
ciphey -t "Tizmg_nv_zxxvhh_gl_gsv_nzk_kovzhv"
Result 'Grant me access to the map please' (y/N): y
Format used:
  atbash
  reverse
  atbash
  leet
  atbash
  reverse
Final result: "Grant me access to the map please"

```

**Version**
 - OS/Distro: [Kali Linux 2019.2]
 - Python version: [Python 3.7.5rc1]
 - Ciphey versions: [Version: 5.5.2, Version: 0.3.1, Version: 0.3.26]
 - Did you use Docker?
----->No

**Verbose Output**
[https://gist.github.com/547y4m/bbebeea865dfe7f63f4269466071edef]

**To Reproduce**

1. What input did you use?
"Tizmg_nv_zxxvhh_gl_gsv_nzk_kovzhv"

2. What flags / arguments did you use?  (-t)
ciphey -t "Tizmg_nv_zxxvhh_gl_gsv_nzk_kovzhv"

**Expected behavior**
I expect that output would be with underscores, but they are missing.

**Comment by SkeletalDemise** [comment]
This is a result of the leetspeak decoder and not the atbash decoder. The atbash decoder doesn't get rid of punctuation or special characters. You can test this with
`ciphey -t "Tizmg_nv_zxxvhh_gl_gsv_nzk_kovzhv" -C regex -p regex.regex=Grant_me` 

The leetspeak decoder replaces underscores with spaces because people usually use underscores to represent spaces. I don't see the problem with your example because it does use underscores as spaces in between words.

**Comment by 547y4m** [comment]
I admit it but while testing same with cyberchef  atbash module it outputs with underscores. So, just feeled that it's any kindof bug or something.

**Comment by SkeletalDemise** [comment]
Well, what do you suggest? Is there a situation that you can think of that would actually make this an issue?

**Comment by 547y4m** [comment]
Yes, you should if it can be easily fixed because i don't think that adding underscores requires much manipulation in code. And as a ciphey contributor/lover i would like that it will perform well and beats other competitor.

The situation/scenario happens with me yesterday, that even i get the decoded text but my flag format is wrong and i have to shift on cyberchef from ciphey to get the correct flag which is really disappointing as a ciphey user. Great tools focuses on every small to big errors.

**Comment by bee-san** [comment]
This problem is because "hello_my_name_is_bee" isn't English unless you take away the underscores. Per [our wiki](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions#ciphey-runs-forever--cant-decrypt-this-input) this is expected behaviour that will change with [our new checkers](https://github.com/Ciphey/Ciphey/wiki/Checkers,-explained#entropy-coming-soon) :smile:
