### ISSUE TITLE
[Chore] setup.py

### ISSUE THREAD

**Issue by noraj** [Ciphey/Ciphey#556]
Hi,

Could you provide a setup.py please?

https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py

**Comment by bee-san** [comment]
No, because setup.py is ancient technology and pyproject is used.

**Comment by noraj** [comment]
Setup.py is not an ancient technology but there are several ways to do it. Doing it with distutils is deprecated but doing it with setuptools is the actual way to do it. It would be much more easier to distribute as we planned to package it into BlackArch linux.

**Comment by bee-san** [comment]
Thanks for that! We'll look into adding it :)

**Comment by harens** [comment]
Hi @noraj! 👋 It's good to see a fellow package manager, so I thought I'd offer some advice.

Just so you know, the [source distribution](https://pypi.org/project/ciphey/#files) from PyPi comes with a `setup.py`. This is how we dealt with it over at [MacPorts](https://www.macports.org) (by downloading the distfiles from PyPi rather than GitHub).

Just another thing, if you're still planning on packaging Ciphey, I personally found packaging its dependency [CipheyCore](https://github.com/Ciphey/CipheyCore) the hardest. I wrote some tips for this that you might find helpful https://github.com/Ciphey/CipheyCore/issues/17.

Let me know if anything's unclear and I'd be happy to help.
