### ISSUE TITLE
Error when running "name 'Decryptor' is not defined"

### ISSUE THREAD

**Issue by BerNo434** [Ciphey/Ciphey#57]
When i try to run ciphey it trows an error
I am new to Python so it could be that i did something wrong when installing

![image](https://user-images.githubusercontent.com/52764786/82961529-e5b98f00-9fbd-11ea-869e-909c4522a361.png)

**Comment by brandonskerritt** [comment]
Hey! Thanks for submitting this. Nothing to do with you, you installed it right. 

Found the bug! `viginere.py` was not run in the multi threaded pool in:
https://github.com/brandonskerritt/Ciphey/blob/master/ciphey/Decryptor/basicEncryption/basic_parent.py

Which means I didn't pick up on it to remove it. It's an unfinished module and thus breaks the system. My fault!

I'll fix it tomorrow, I know exactly what the bug is :)

**Comment by brandonskerritt** [comment]
Now fixed in the latest release, thanks!
