### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by savetheword** [Ciphey/Ciphey#720]
└─# ./ciphey.py -t                                                                                                                                                                                          100 ⨯
./ciphey.py: 13: 
 ██████╗██╗██████╗ ██╗  ██╗███████╗██╗   ██╗
██╔════╝██║██╔══██╗██║  ██║██╔════╝╚██╗ ██╔╝
██║     ██║██████╔╝███████║█████╗   ╚████╔╝
██║     ██║██╔═══╝ ██╔══██║██╔══╝    ╚██╔╝
╚██████╗██║██║     ██║  ██║███████╗   ██║
https://github.com/Ciphey
https://github.com/Ciphey/Ciphey/wiki

The cycle goes:
main -> argparsing (if needed) -> call_encryption -> new Ciphey object -> decrypt() -> produceProbTable ->
one_level_of_decryption -> decrypt_normal
: File name too long
./ciphey.py: 14: import: not found
./ciphey.py: 15: import: not found
./ciphey.py: 16: from: not found
./ciphey.py: 18: import: not found
./ciphey.py: 19: from: not found
./ciphey.py: 20: import: not found
./ciphey.py: 21: from: not found
./ciphey.py: 22: from: not found
./ciphey.py: 24: from: not found
./ciphey.py: 26: Syntax error: word unexpected (expecting ")")

**Comment by SkeletalDemise** [comment]
I'm closing this because you didn't fill out the issue template which is required because your Python version, Ciphey version, etc. are important to know. You also can't run Ciphey like that, please use `pip install ciphey -U`

It seems like you're using an old version as well because Ciphey doesn't use a probability table anymore.
Look at the installation instructions for more help: https://github.com/Ciphey/Ciphey/wiki/Installation
