### ISSUE TITLE
failed to decode Base64

### ISSUE THREAD

**Issue by jepunband** [Ciphey/Ciphey#726]
Ciphey failed to decipher RVJBTkcgU0VMVUFTIDgwIEVLQVIgKOKAnFByb2playB0ZXJzZWJ1dOKAnSk , 

but i could decipher it here: 
https://emn178.github.io/online-tools/base64_decode.html

**Comment by SkeletalDemise** [comment]
Hello. I'm closing this issue because the plaintext of your Base64 is `ERANG SELUAS 80 EKAR (“Projek tersebut”)` which is Malay for `80 ACRES OF ERANG (“The Project”)` it seems. Ciphey only supports English, URLs, email addresses, phone numbers, etc.

You can read about Ciphey's checkers here: https://github.com/Ciphey/Ciphey/wiki/Checkers,-explained
