### ISSUE TITLE
Adding base65536 decoder

### ISSUE THREAD

**Issue by kn1-gh7** [Ciphey/Ciphey#787]
### Problem:
Encountered decoding this in a recent month long CTF. I suggest adding its decoder.

### Solution:
The implementation for base65536 is standard. So adding a decoder should not be very tough. The priority could be around 0.05.

**Comment by SkeletalDemise** [comment]
That already exists, it's just not in the newest release.
https://github.com/Ciphey/Ciphey/wiki/Supported-Ciphers

Additionally, we are not working on Ciphey anymore. We are remaking Ciphey in Rust due to numerous reasons. Read the pinned issue: https://github.com/Ciphey/Ciphey/issues/764

Base65536 is already in Ares.
https://github.com/bee-san/Ares/issues/61

**Comment by kn1-gh7** [comment]
Yes, I just realised sorry
