### ISSUE TITLE
Configuration overhaul

### ISSUE THREAD

**Issue by Cyclic3** [Ciphey/Ciphey#94]
### Problem
Many modules require dictionaries, and we keep defaulting to various ones under cipheydists, usually an English distribution of some form. Whilst this creates i18n issues, it also blocks users from doing password decryption and other things. Many modules from #90 could also use such a system, to stop there having to be a repeated flag.

This is just one instance of an underlying problem: the lack of proper 

### Solution
We can make a global dictionary flag, that is propagated to the rest of the system. I like `-w` for `wordlist`

This would need to be passed around all the modules, as we would have no idea how deep this would go. Since we are planning to make this somewhat usable as a library, I have to suppress my inner C programmer telling me to use global variables. 

After discussion with @brandonskerritt, we came up with something akin to the internal data packet, but for arguments: a dictionary of all parsed arguments will be passed around all the major modules.

We should store default values for this, as well as less common configuration options in a separate config file. The `-c` flag could be used to denote the location of the config file, perhaps with a default value in the user's home directory.

**Comment by brandonskerritt** [comment]
This is similar to #93 however since the previous issue was poorly written and hard to understand, this issue is being kept instead.

It is ideal for us to create some sort of settings.yaml file, partly to store the various flags but also to store user settings.

The user may have preferences for how Ciphey is run in the future such as:
* Skip NN
* Only use filtration system
* Use REGEX language detection interface
* Make the output greppable
It would be ideal to store these into a settings file. The user can call `ciphey -s` to signify the use of a settings file. If they call `ciphey --wordlist` we can temporarily store the arguments in the settings file.

We can create an object which interacts with this file and pass it through the system with the internal data packet we use.

**Comment by Cyclic3** [comment]
Thanks for hijacking my issue! /s

You're right, this should be covered as the entire thing, so I will update the initial proposal.

**Comment by Cyclic3** [comment]
Covered in #104
